# Generated by Django 5.2.12 on 2026-03-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_bill_xero_account_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('submitted', 'Submitted'), ('marked_paid', 'Marked Paid'), ('voided', 'Voided'), ('cancelled', 'Cancelled'), ('status_changed', 'Status Changed'), ('published_to_xero', 'Published to Xero'), ('attachment_uploaded', 'Attachment Uploaded'), ('attachment_deleted', 'Attachment Deleted'), ('payment_created', 'Payment Created'), ('payment_updated', 'Payment Updated'), ('payment_deleted', 'Payment Deleted')], max_length=100),
        ),
    ]
