# Generated by Django 5.2.12 on 2026-04-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_fix_fk_ondelete_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='billattachment',
            name='xero_attachment_id',
            field=models.CharField(blank=True, default='', help_text='Xero FileId returned after uploading to the Xero Files API.', max_length=36),
        ),
        migrations.AddField(
            model_name='billattachment',
            name='xero_filename',
            field=models.CharField(blank=True, default='', help_text='Slot-based filename used when the file was uploaded to Xero.', max_length=255),
        ),
    ]
