# Generated by Django 5.2.12 on 2026-04-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0008_bill_attachment_xero_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('returned', 'Returned'), ('authorised', 'Authorised'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('voided', 'Voided'), ('cancelled', 'Cancelled'), ('sync_failed', 'Sync Failed')], default='draft', max_length=30),
        ),
    ]
